use super::{AgentCapabilities, AgentProfile, AgentSpawn, NoiseFilter, TranscriptSource};
use crate::structs::ids::ProfileId;
use crate::traits::AgentTrait;
use std::path::Path;

pub struct ClaudeAgent;

// Measured against 22 real sessions on 2026-08-26. Every shape here arrives
// under the person's role and none of it was typed by them.
//
// The wrapper rows are matched whole, never as substrings, so a person asking
// what `<system-reminder>` means keeps their message. A local-command block
// opens and closes with different tags, which is why it also has a prefix row:
// the prefix is what catches it and the pair is what documents the shape.
static CLAUDE_NOISE: NoiseFilter = NoiseFilter {
    wrappers: &[
        ("<system-reminder>", "</system-reminder>"),
        ("<command-name>", "</command-args>"),
        ("<local-command-stdout>", "</local-command-stdout>"),
        ("<task-notification>", "</task-notification>"),
    ],
    prefixes: &[
        "Caveat: The messages below were generated by the user while running local commands.",
        "Another Claude session sent a message:",
        "<command-name>",
        "<local-command-stdout>",
        "<task-notification>",
        "<bash-input>",
        "<bash-stdout>",
        // Dropped as text and re-emitted structurally, because it is a
        // deliberate act rather than something to hide. 179 interrupts carry a
        // field naming the message they stopped; 46 carry only this sentence,
        // so the reader detects both and renders one status part either way.
        "[Request interrupted by user]",
    ],
};

impl ClaudeAgent {
    pub const BINARY: &'static str = "claude";

    /// The directory name Claude Code gives a working directory under
    /// `~/.claude/projects/`.
    ///
    /// Every character outside `[A-Za-z0-9]` becomes a dash. Measured against 31
    /// directories on a real machine by re-flattening each session's own `cwd`
    /// field; 31 matched.
    ///
    /// The mapping is not reversible - a colon, a separator, a dot and a space
    /// all collapse to the same dash - so nothing may recover a working
    /// directory from a directory name. The records carry `cwd` as a field.
    pub fn project_directory(cwd: &str) -> String {
        cwd.chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .collect()
    }
}

impl AgentTrait for ClaudeAgent {
    fn binary(&self) -> &'static str {
        Self::BINARY
    }

    fn launch_command(&self, spawn: &AgentSpawn) -> Vec<String> {
        if let Some(session) = &spawn.resume {
            return self.resume_command(session);
        }

        let mut argv = vec![Self::BINARY.to_string()];

        if let Some(prompt) = &spawn.prompt {
            argv.push(prompt.clone());
        }

        argv
    }

    fn resume_command(&self, session_id: &str) -> Vec<String> {
        vec![
            Self::BINARY.to_string(),
            "--resume".to_string(),
            session_id.to_string(),
        ]
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            resume: true,
            interrupt: true,
            file_upload: true,
            questions: true,
        }
    }

    fn profile(&self) -> AgentProfile {
        AgentProfile {
            id: ProfileId(Self::BINARY.to_string()),
            label: "Claude Code".to_string(),
            description: None,
            // Read from the binary once a version probe exists. Absent is not a
            // guess, and a wrong version here is worse than no version.
            version: None,
            supports_resume: true,
            provides_transcript: true,
        }
    }

    fn transcript_source(&self, home: &Path, cwd: &str, session: &str) -> TranscriptSource {
        TranscriptSource::JsonLines {
            path: home
                .join(".claude")
                .join("projects")
                .join(Self::project_directory(cwd))
                .join(format!("{session}.jsonl")),
        }
    }

    fn noise_filter(&self) -> &'static NoiseFilter {
        &CLAUDE_NOISE
    }

    fn file_push_tools(&self) -> &'static [&'static str] {
        &["SendUserFile"]
    }

    fn question_tools(&self) -> &'static [&'static str] {
        &["AskUserQuestion"]
    }

    fn diff_tools(&self) -> &'static [&'static str] {
        &["Edit", "Write", "NotebookEdit"]
    }

    fn todo_tools(&self) -> &'static [&'static str] {
        &["TodoWrite"]
    }
}
