use serde::{Deserialize, Serialize};
use ts_rs::TS;

// The prefix is part of the value, not stripped on parse. Keeping it in the
// string is what makes a mixed-up id fail at the boundary instead of resolving
// to the wrong entity.
macro_rules! prefixed_id {
    ($name:ident, $prefix:literal, $doc:literal) => {
        #[doc = $doc]
        #[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize, TS)]
        #[ts(export, export_to = "./../../client/src/js/bindings/")]
        pub struct $name(String);

        impl $name {
            pub const PREFIX: &'static str = $prefix;

            pub fn parse(value: &str) -> Option<Self> {
                let rest = value.strip_prefix(Self::PREFIX)?;

                if rest.is_empty() {
                    return None;
                }

                Some(Self(value.to_owned()))
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }

            pub fn mint(suffix: &str) -> Self {
                Self(format!("{}{}", Self::PREFIX, suffix))
            }
        }
    };
}

// Values that come from outside tethera: an agent's own record id, a catalog
// key, a client-generated request id. Still opaque, still never parsed.
macro_rules! plain_id {
    ($name:ident, $doc:literal) => {
        #[doc = $doc]
        #[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize, TS)]
        #[ts(export, export_to = "./../../client/src/js/bindings/")]
        pub struct $name(pub String);

        impl $name {
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl From<String> for $name {
            fn from(value: String) -> Self {
                Self(value)
            }
        }
    };
}

prefixed_id!(ServerId, "sv_", "One machine.");
prefixed_id!(SessionId, "ss_", "One terminal-backend session.");
prefixed_id!(WorkspaceId, "ws_", "One workspace within a session.");
prefixed_id!(TabId, "tb_", "One tab within a workspace.");
prefixed_id!(PaneId, "pn_", "One pane within a tab.");
prefixed_id!(
    ConversationId,
    "cv_",
    "One agent conversation, which outlives any pane."
);
prefixed_id!(AssetId, "as_", "One file the server's scan has seen.");
prefixed_id!(DeviceId, "dv_", "One enrolled client.");
prefixed_id!(QuestionId, "qs_", "One question an agent is blocked on.");

plain_id!(
    TurnId,
    "A transcript record, stable across reads, derived from the source."
);
plain_id!(ProfileId, "A row in the machine's agent catalog.");
plain_id!(RequestId, "One enrollment attempt, generated by the client.");
